# Generated by Django 3.2.3 on 2021-05-26 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dist_code', models.IntegerField(default=0)),
                ('population_total', models.IntegerField(default=0)),
                ('population_male', models.IntegerField(default=0)),
                ('population_female', models.IntegerField(default=0)),
                ('population_child_total', models.IntegerField(default=0)),
                ('population_child_male', models.IntegerField(default=0)),
                ('population_child_female', models.IntegerField(default=0)),
                ('literate_total', models.IntegerField(default=0)),
                ('literate_male', models.IntegerField(default=0)),
                ('literate_female', models.IntegerField(default=0)),
                ('sex_ratio', models.IntegerField(default=0)),
                ('child_sex_ratio', models.IntegerField(default=0)),
                ('effective_literacy_rate_total', models.FloatField(default=0.0)),
                ('effective_literacy_rate_male', models.FloatField(default=0.0)),
                ('effective_literacy_rate_female', models.FloatField(default=0.0)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('total_graduates', models.IntegerField(default=0)),
                ('male_graduates', models.IntegerField(default=0)),
                ('female_graduates', models.IntegerField(default=0)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.state')),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
